version: '3.8'

services:
  epm-backend-dev:
    image: "${DOCKER_REGISTRY_URL}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
    container_name: epm-api-be-dev
    environment:
      - JWT_AT_SECRET=${JWT_AT_SECRET}
      - JWT_RT_SECRET=${JWT_RT_SECRET}
      - DB_HOST=epm-mysql-dev
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    ports:
      - ${BE_EXPOSED_PORT}:3000
    depends_on:
      - epm-mysql-dev
    networks: 
      - epm-network-dev
    restart: unless-stopped

  epm-mysql-dev:
    image: mysql:8.0
    container_name: epm-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_EXPOSED_PORT}:3306"
    volumes:
      - ${DOCKER_DB_MOUNTPOINT}:/var/lib/mysql
    networks:
      - epm-network-dev
    restart: unless-stopped

networks:
  epm-network-dev: